import js from '@eslint/js';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import prettierPlugin from 'eslint-plugin-prettier';
import eslintConfigPrettier from 'eslint-config-prettier';

export default [
    // `*.css.d.ts` are generated by `npm run gen:css-types` and gitignored, so a
    // clean checkout never has them. Linting them locally produced ~1400 prettier
    // warnings on machine-written files and hid the real ones.
    { ignores: ['build', 'dist', 'node_modules', '**/*.css.d.ts'] },
    { files: ['**/*.{js,mjs,cjs,ts,tsx}'] },
    {
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node
            },
            parserOptions: {
                // Pin the TS root to this config's directory so typescript-eslint
                // doesn't bail when the editor lints from the workspace root,
                // where both this client and the parent server are candidate roots.
                tsconfigRootDir: import.meta.dirname,
                ecmaFeatures: {
                    jsx: true
                }
            }
        }
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        plugins: {
            react: react,
            'react-hooks': reactHooks,
            prettier: prettierPlugin
        },
        rules: {
            ...react.configs.recommended.rules,
            // Un hook après un retour anticipé fait tomber l'écran le jour où le
            // retour se déclenche, et pas avant : seul le lint le voit à temps.
            'react-hooks/rules-of-hooks': 'error',
            'react/react-in-jsx-scope': 'off',
            'react/prop-types': 'off',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                {
                    args: 'all',
                    argsIgnorePattern: '^_',
                    caughtErrors: 'all',
                    caughtErrorsIgnorePattern: '^_',
                    destructuredArrayIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    ignoreRestSiblings: true
                }
            ],
            '@typescript-eslint/no-explicit-any': 'warn',
            'no-control-regex': 'off',
            'dot-notation': 'off',
            'no-bitwise': 'off',
            '@typescript-eslint/no-empty-object-type': 'off',
            'max-len': [
                'error',
                {
                    code: 120,
                    ignoreUrls: true,
                    ignoreComments: true,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true
                }
            ],
            'prettier/prettier': 'warn'
        },
        settings: {
            react: {
                version: 'detect'
            }
        }
    },
    eslintConfigPrettier
];
