# Build context is this dir (DevEye). Ignore heavy/local files.
**/node_modules
**/.git
**/dist
**/build
**/client/build
**/.env
**/.env.*
!**/.env.template
**/logs/*.log
**/*.log
**/.DS_Store
**/coverage
**/.vscode
**/target
