// Généré par `npm run gen:db-schema` depuis une base migrée. Ne pas éditer.

/** Les tables du socle, colonne par colonne, telles que `mysql2` les rend. */
export interface Tables {
    _migrations: {
        name: string;
        applied_at: number;
    };
    audience_daily: {
        site_id: number;
        day: number;
        views: number;
        events: number;
        sessions: number;
        visitors: number;
    };
    audience_events: {
        id: number;
        site_id: number;
        session_id: number;
        ts: number;
        kind: number;
        path_id: number | null;
        name_id: number | null;
    };
    audience_funnel_steps: {
        id: number;
        funnel_id: number;
        site_id: number;
        position: number;
        match_kind: string;
        label_ref: string;
        content: string;
    };
    audience_funnels: {
        id: number;
        site_id: number;
        name_ref: string;
        sort_order: number;
        content: string;
        created: number;
    };
    audience_labels: {
        id: number;
        site_id: number;
        kind: string;
        label_ref: string;
        content: string;
    };
    audience_sessions: {
        id: number;
        site_id: number;
        visitor_ref: string;
        started_at: number;
        last_at: number;
        views: number;
        entry_path_id: number | null;
        referrer_id: number | null;
        browser_id: number | null;
        os_id: number | null;
        device_id: number | null;
        timezone_id: number | null;
        language_id: number | null;
        identity_id: number | null;
        tz_offset: number | null;
        screen_width: number | null;
    };
    audience_sites: {
        id: number;
        workspace_id: number;
        public_key: string;
        name_ref: string;
        platform: string;
        visitor_mode: string;
        origins: string | null;
        active: number;
        retention_days: number;
        forms_auto: number;
        submission_ip_quota: number;
        submission_ban_quota: number;
        form_hourly_quota: number;
        event_ip_quota: number;
        sort_order: number;
        last_event_at: number | null;
        content: string;
        created: number;
    };
    backup_destinations: {
        id: number;
        workspace_id: number;
        kind: string;
        device_id: string | null;
        path_style: number;
        status: string;
        checked_at: number | null;
        content: string;
        secret_enc: string;
        created: number;
    };
    backup_jobs: {
        id: number;
        workspace_id: number;
        destination_id: number;
        source_kind: string;
        source_id: number | null;
        enabled: number;
        schedule_kind: string;
        schedule_hour: number;
        schedule_weekday: number;
        schedule_day: number;
        keep_last: number;
        encryption: string;
        next_run_at: number | null;
        content: string;
        created: number;
    };
    backup_runs: {
        id: number;
        job_id: number;
        workspace_id: number;
        status: string;
        started_at: number;
        finished_at: number | null;
        size_bytes: number;
        checksum: string | null;
        encrypted: number;
        triggered_by_user_id: number | null;
        pruned: number;
        content: string;
    };
    database_alerts: {
        id: number;
        database_id: number;
        workspace_id: number;
        enabled: number;
        combinator: string;
        firing: number;
        last_check_at: number | null;
        last_fired_at: number | null;
        last_error: string | null;
        content: string;
        created: number;
    };
    database_connections: {
        id: number;
        workspace_id: number;
        engine: string;
        name_ref: string;
        sort_order: number;
        monitor_enabled: number;
        interval_seconds: number;
        last_check_at: number | null;
        last_elapsed_ms: number | null;
        status: string;
        last_error: string | null;
        server_version: string | null;
        size_bytes: number | null;
        table_count: number | null;
        content: string;
        secret_enc: string | null;
        access_content: string | null;
        access_secret_enc: string | null;
        created: number;
    };
    debug_runs: {
        id: number;
        origin: string;
        kind: 'e2e' | 'bench';
        status: 'running' | 'passed' | 'failed' | 'aborted';
        started: number;
        finished: number | null;
        user_id: number | null;
        report: string;
    };
    deploy_targets: {
        id: number;
        workspace_id: number;
        credential_id: number | null;
        device_id: string | null;
        provider: string;
        target_kind: string;
        external_id: string;
        sort_order: number;
        content: string;
        synced_at: number | null;
        created: number;
    };
    deployments: {
        id: number;
        target_id: number;
        workspace_id: number;
        external_id: string | null;
        status: string;
        triggered_by_user_id: number | null;
        started_at: number;
        finished_at: number | null;
        notified: number;
        content: string;
    };
    device_baseline: {
        id: number;
        device_id: string;
        kind: string;
        item_key: string;
        item_hash: Buffer;
        first_seen: number;
        last_seen: number;
        samples: number;
        attrs: unknown;
    };
    device_findings: {
        id: number;
        device_id: string;
        rule: string;
        dedup_hash: Buffer;
        severity: number;
        state: string;
        subject: string;
        evidence: unknown;
        snapshot_ts: number | null;
        first_seen: number;
        last_seen: number;
        occurrences: number;
        notified: number;
        acked_by: number | null;
        acked_at: number | null;
    };
    device_link_codes: {
        code: string;
        user_id: number;
        workspace_id: number;
        expires_at: number;
        max_uses: number;
        uses: number;
        used_at: number | null;
        created: number;
    };
    device_metrics: {
        id: number;
        device_id: string;
        ts: number;
        cpu_percent: number;
        mem_used_bytes: number;
        mem_total_bytes: number;
        disk_used_bytes: number;
        disk_total_bytes: number;
        net_rx_bytes: number;
        net_tx_bytes: number;
        users_count: number;
        load_avg_1: number | null;
        cpu_temp_c: number | null;
        uptime_seconds: number | null;
        process_count: number | null;
        active_connections: number | null;
        gpu_percent: number | null;
        disk_read_bytes: number | null;
        disk_write_bytes: number | null;
        battery_percent: number | null;
        battery_charging: number | null;
        pinned: number;
    };
    device_presence: {
        id: number;
        device_id: string;
        ts: number;
        online: number;
    };
    device_process_samples: {
        device_id: string;
        ts: number;
        kind: 'top' | 'all';
        proc_count: number;
        payload_bytes: number;
        payload: Buffer;
        pinned: number;
    };
    devices: {
        id: string;
        owner_id: number;
        workspace_id: number;
        name: string;
        fingerprint: string;
        platform: string;
        status: string;
        token_hash: string;
        token_hash_prev: string | null;
        last_seen: number | null;
        created: number;
        report_json: string | null;
        retention_days: number | null;
        terminal_default_user: string | null;
        terminal_close_on_exit: number;
        metric_interval_seconds: number | null;
        process_capture: 'off' | 'top' | 'all' | null;
        status_before_delete: string | null;
        delete_error: string | null;
        agent_version: string | null;
        agent_target: string | null;
        sort_order: number;
    };
    feature_domains: {
        id: number;
        workspace_id: number;
        feature: string;
        host: string;
        token: string;
        dns_state: string;
        dns_error: string;
        probe_state: string;
        probe_error: string;
        verified_at: number | null;
        checked_at: number | null;
        failures: number;
        next_probe_at: number | null;
        created: number;
    };
    feature_kv: {
        workspace_id: number;
        feature: string;
        k: string;
        mode: 'server' | 'private' | 'none';
        value: string;
        updated: number;
    };
    feature_maintenance: {
        feature: string;
        level: 'requests' | 'full' | 'preview';
        updated: number;
        updated_by: number | null;
    };
    feedback: {
        id: number;
        uid: number;
        workspace_id: number | null;
        kind: string;
        message: string;
        snapshot: unknown | null;
        status: string;
        ip: string;
        app_version: string;
        created: number;
        handled_at: number | null;
        handled_by: number | null;
    };
    finance_accounts: {
        id: number;
        workspace_id: number;
        kind: string;
        color: string;
        initial_balance: number;
        opened_on: Date;
        archived: number;
        sort_order: number;
        content: string;
        created: number;
    };
    finance_categories: {
        id: number;
        workspace_id: number;
        flow: string;
        color: string;
        icon: string;
        role: string | null;
        sort_order: number;
        content: string;
        created: number;
    };
    finance_config: {
        workspace_id: number;
        invoicing_account_id: number | null;
        invoicing_category_id: number | null;
        invoicing_version: string | null;
        legal_status: string | null;
        micro_activity: string | null;
        provision_rate_bp: number | null;
        income_tax_prepaid: number;
        declaration_period: string | null;
        tracking_since: Date | null;
    };
    finance_recurring: {
        id: number;
        workspace_id: number;
        account_id: number;
        transfer_account_id: number | null;
        category_id: number | null;
        kind: string;
        amount: number;
        vat_amount: number | null;
        frequency: string;
        interval_count: number;
        next_date: Date;
        anchor_day: number | null;
        end_date: Date | null;
        last_posted_date: Date | null;
        automatic: number;
        active: number;
        content: string;
        created: number;
    };
    finance_transactions: {
        id: number;
        workspace_id: number;
        account_id: number;
        transfer_account_id: number | null;
        category_id: number | null;
        recurring_id: number | null;
        source: string | null;
        source_ref: string | null;
        kind: string;
        amount: number;
        vat_amount: number | null;
        date: Date;
        cleared: number;
        content: string;
        created: number;
        updated: number;
    };
    git_branches: {
        id: number;
        repo_id: number;
        workspace_id: number;
        name_ref: string;
        head_sha: string | null;
        ahead_count: number | null;
        behind_count: number | null;
        compared_sha: string | null;
        is_default: number;
        updated_at: number | null;
        content: string;
    };
    git_commit_authors: {
        id: number;
        repo_id: number;
        author_ref: string;
        workspace_id: number;
        user_id: number | null;
        content: string;
        created: number;
    };
    git_commits: {
        id: number;
        repo_id: number;
        workspace_id: number;
        sha: string;
        committed_at: number;
        author_ref: string;
        parents: unknown | null;
        content: string;
    };
    git_pull_requests: {
        id: number;
        repo_id: number;
        workspace_id: number;
        number: number;
        state: string;
        author_ref: string | null;
        created_at: number;
        updated_at: number;
        merged_at: number | null;
        closed_at: number | null;
        content: string;
    };
    git_releases: {
        id: number;
        repo_id: number;
        workspace_id: number;
        tag_ref: string;
        published_at: number;
        is_prerelease: number;
        content: string;
    };
    git_repos: {
        id: number;
        workspace_id: number;
        credential_id: number | null;
        provider: string;
        slug_ref: string;
        enabled: number;
        sort_order: number;
        default_branch: string | null;
        last_sync_at: number | null;
        last_sync_error: string | null;
        sync_state: string | null;
        content: string;
        created: number;
    };
    instance_settings: {
        name: string;
        origin: string;
        value: string;
        updated: number;
        updated_by: number | null;
    };
    item_role_grants: {
        workspace_id: number;
        feature: string;
        item_id: string;
        role_id: number;
        access: string | null;
        extra_overrides: unknown | null;
    };
    item_shares: {
        workspace_id: number;
        feature: string;
        item_id: string;
        home_workspace_id: number;
        shared_by_user_id: number;
        created: number;
        sort_order: number;
    };
    logs: {
        id: number;
        uid: number;
        ip: string;
        source: string;
        category: string;
        level: number;
        action: string;
        description: string;
        metadata: unknown | null;
        date: number;
    };
    mail_accounts: {
        id: number;
        user_id: number;
        workspace_id: number;
        sort_order: number;
        display_name_enc: string;
        email_address_enc: string;
        security_tier: string;
        auth_method: string;
        enabled: number;
        sync_interval_seconds: number;
        last_sync_at: number | null;
        last_sync_status: string;
        last_error_at: number | null;
        last_sync_error_enc: string | null;
        credentials_enc: string;
        created: number;
    };
    mail_folders: {
        id: number;
        account_id: number;
        imap_path: string;
        name_enc: string;
        special_use: string;
        sort_order: number;
        uid_validity: number | null;
        last_seen_uid: number | null;
        first_seen_uid: number | null;
        unread_count: number;
        total_count: number;
    };
    mail_messages: {
        id: number;
        folder_id: number;
        uid: number;
        envelope_enc: string;
        date: number;
        seen: number;
        flagged: number;
        answered: number;
        has_attachments: number;
    };
    mail_settings: {
        workspace_id: number;
        external_scan_enabled_default: number;
        trusted_image_domains: string | null;
        body_render_mode: string;
    };
    note_folders: {
        id: number;
        user_id: number;
        workspace_id: number;
        content: string;
        sort_order: number;
        created: number;
    };
    notes: {
        id: number;
        user_id: number;
        workspace_id: number;
        folder_id: number | null;
        sort_order: number;
        content: string;
        is_private: number;
        archived_at: number | null;
        updated: number;
        created: number;
    };
    notification_channels: {
        id: number;
        workspace_id: number;
        feature: string;
        kind: string;
        label_enc: string | null;
        target_enc: string | null;
        mail_account_id: number | null;
        enabled: number;
        position: number;
        created: number;
    };
    notification_route_channels: {
        route_id: number;
        channel_id: number;
    };
    notification_routes: {
        id: number;
        workspace_id: number;
        feature: string;
        item_id: number;
    };
    osint_lookups: {
        id: string;
        workspace_id: number;
        user_id: number;
        kind: string;
        query_enc: string;
        created: number;
    };
    osint_provider_keys: {
        workspace_id: number;
        provider: string;
        key_enc: string;
        created: number;
    };
    passwords: {
        id: number;
        user_id: number;
        workspace_id: number;
        content: string;
        date: number;
    };
    pending_signups: {
        id: number;
        email: string;
        username: string;
        token_hash: string;
        watch_hash: string;
        plan: string | null;
        opened_at: number | null;
        completed_at: number | null;
        expires_at: number;
        created: number;
        terms_accepted_at: number | null;
    };
    project_audience_links: {
        project_id: number;
        site_id: number;
        workspace_id: number;
        created: number;
    };
    project_card_deps: {
        card_id: number;
        blocked_by_card_id: number;
        project_id: number;
        created: number;
    };
    project_card_reads: {
        card_id: number;
        user_id: number;
        workspace_id: number;
        last_read_message_id: number;
        read_at: number;
    };
    project_cards: {
        id: number;
        project_id: number;
        workspace_id: number;
        column_id: number | null;
        sort_order: number;
        author_user_id: number | null;
        assignee_user_id: number | null;
        priority: number;
        start_date: number | null;
        due_date: number | null;
        estimate_minutes: number | null;
        required_open_count: number;
        milestone_id: number | null;
        archived_at: number | null;
        message_count: number;
        last_message_at: number | null;
        content: string;
        created: number;
        updated: number;
    };
    project_columns: {
        id: number;
        project_id: number;
        workspace_id: number;
        sort_order: number;
        counts_as_done: number;
        wip_limit: number | null;
        content: string;
        created: number;
    };
    project_database_links: {
        project_id: number;
        database_id: number;
        workspace_id: number;
        created: number;
    };
    project_deploy_links: {
        project_id: number;
        target_id: number;
        workspace_id: number;
        created: number;
    };
    project_events: {
        id: number;
        project_id: number;
        workspace_id: number;
        actor_user_id: number | null;
        kind: string;
        ref_type: string | null;
        ref_id: number | null;
        created: number;
        content: string;
    };
    project_messages: {
        id: number;
        card_id: number;
        project_id: number;
        workspace_id: number;
        author_user_id: number | null;
        mentions: unknown | null;
        created: number;
        edited: number | null;
        content: string;
    };
    project_milestones: {
        id: number;
        project_id: number;
        workspace_id: number;
        due_date: number;
        reached_at: number | null;
        sort_order: number;
        content: string;
        created: number;
    };
    project_repo_links: {
        project_id: number;
        workspace_id: number;
        repo_id: number;
        created: number;
    };
    project_uptime_links: {
        project_id: number;
        service_id: number;
        workspace_id: number;
        created: number;
    };
    projects: {
        id: number;
        workspace_id: number;
        user_id: number | null;
        status: string;
        security_tier: string;
        version_source: string;
        show_overview: number;
        show_timeline: number;
        sort_order: number;
        start_date: number | null;
        due_date: number | null;
        archived_at: number | null;
        content: string;
        created: number;
        updated: number;
    };
    quota_pauses: {
        quota_key: string;
        item_id: string;
        owner_user_id: number;
        workspace_id: number;
        created: number;
    };
    quota_rechecks: {
        owner_user_id: number;
        due_at: number;
    };
    refresh_tokens: {
        jti: string;
        user_id: number;
        session_id: string;
        token_hash: string;
        expires_at: number;
        created_at: number;
        revoked_at: number | null;
    };
    remote_instances: {
        id: number;
        user_id: number;
        label: string;
        origin: string;
        sort_order: number;
        created: number;
    };
    sentinel_allowlist: {
        id: number;
        workspace_id: number;
        device_id: string | null;
        rule: string;
        subject: string;
        subject_hash: Buffer;
        reason: string | null;
        created_by: number;
        created: number;
    };
    site_maintenance: {
        id: number;
        active: number;
        message: string | null;
        env_notice_dismissed: number;
        updated: number;
        updated_by: number | null;
        priority: number;
        priority_updated: number | null;
        priority_by: number | null;
    };
    sync_device_files: {
        id: number;
        share_id: number;
        device_id: string;
        rel_path: string;
        rel_path_hash: string;
        kind: string;
        hash: string;
        size: number;
        mtime: number;
        mode: number | null;
        synced_at: number;
    };
    sync_events: {
        id: number;
        share_id: number;
        device_id: string | null;
        rel_path: string | null;
        message: string;
        created: number;
    };
    sync_exclusions: {
        id: number;
        share_id: number;
        kind: string;
        pattern: string;
        created: number;
    };
    sync_files: {
        id: number;
        share_id: number;
        rel_path: string;
        rel_path_hash: string;
        kind: string;
        hash: string;
        size: number;
        mtime: number;
        mode: number | null;
        source_device_id: string | null;
        state: string;
        created: number;
        updated: number;
    };
    sync_meta: {
        k: string;
        v: string;
    };
    sync_sessions: {
        id: number;
        share_id: number;
        device_id: string;
        state: string;
        files_total: number;
        bytes_total: number;
        files_done: number;
        bytes_done: number;
        error: string | null;
        started: number;
        finished: number | null;
    };
    sync_share_devices: {
        id: number;
        share_id: number;
        device_id: string;
        local_path: string;
        status: string;
        last_sync_at: number | null;
        created: number;
    };
    sync_shares: {
        id: number;
        user_id: number;
        workspace_id: number;
        name: string;
        storage_key: string;
        status: string;
        sort_order: number;
        backup_prune_enabled: number;
        backup_limit_bytes: number | null;
        created: number;
        updated: number;
        conflict_policy: string;
        snapshot_enabled: number;
        snapshot_interval_hours: number;
        snapshot_keep_days: number;
        rate_up_bps: number | null;
        rate_down_bps: number | null;
        trash_keep_days: number;
        integrity_scan_enabled: number;
    };
    sync_snapshot_files: {
        snapshot_id: number;
        rel_path: string;
        rel_path_hash: string;
        kind: string;
        hash: string;
        size: number;
        mtime: number;
        mode: number | null;
    };
    sync_snapshots: {
        id: number;
        share_id: number;
        kind: string;
        label: string | null;
        file_count: number;
        total_bytes: number;
        created: number;
    };
    sync_versions: {
        id: number;
        share_id: number;
        rel_path: string;
        hash: string;
        size: number;
        mtime: number | null;
        source_device_id: string | null;
        reason: string;
        created: number;
    };
    uptime_checks: {
        id: number;
        service_id: number;
        checked_at: number;
        up: number;
        http_status: number | null;
        response_ms: number | null;
        error: string | null;
    };
    uptime_daily: {
        service_id: number;
        day: number;
        checks: number;
        up_checks: number;
        total_ms: number;
        ms_samples: number;
        min_ms: number | null;
        max_ms: number | null;
    };
    uptime_incidents: {
        id: number;
        service_id: number;
        started_at: number;
        ended_at: number | null;
        http_status: number | null;
        error: string | null;
        notified: number;
    };
    uptime_services: {
        id: number;
        user_id: number;
        workspace_id: number;
        content: string;
        kind: string;
        method: string;
        expected_status: number | null;
        interval_seconds: number;
        timeout_seconds: number;
        failure_threshold: number;
        retention_days: number | null;
        enabled: number;
        sort_order: number;
        status: string;
        consecutive_failures: number;
        last_checked_at: number | null;
        last_response_ms: number | null;
        last_http_status: number | null;
        last_error: string | null;
        baseline_enc: string | null;
        created: number;
    };
    user_2fa: {
        user_id: number;
        secret_enc: string;
        enabled: number;
        created: number;
        confirmed_at: number | null;
        last_used_counter: number | null;
    };
    user_2fa_backup_codes: {
        id: number;
        user_id: number;
        code_hash: string;
        used_at: number | null;
        created: number;
    };
    user_secret_keys: {
        user_id: number;
        dek_wrapped: string;
        open_dek_wrapped: string | null;
        wrap_mode: 'server' | 'password';
        kdf_salt: Buffer | null;
        recovery_wrapped: string | null;
        recovery_salt: Buffer | null;
        recovery_version: number;
        version: number;
        created: number;
        updated: number;
    };
    users: {
        id: number;
        email: string;
        username: string;
        password_hash: string;
        avatar: string;
        color: string;
        role: string;
        status: 'active' | 'suspended';
        personal_workspace_id: number;
        default_workspace_id: number | null;
        settings: unknown;
        re_auth_interval: number | null;
        last_login: number;
        created: number;
        terms_accepted_at: number | null;
        e2e_run: string | null;
    };
    weather_locations: {
        id: string;
        user_id: number;
        workspace_id: number;
        label: string;
        latitude: number;
        longitude: number;
        format: string;
        days: number;
        provider: string;
        position: number;
        created: number;
        is_primary: number;
    };
    weather_provider_keys: {
        workspace_id: number;
        provider: string;
        key_enc: string;
        created: number;
    };
    workspace_members: {
        id: number;
        user_id: number;
        workspace_id: number;
        role_id: number | null;
        date: number;
    };
    workspace_roles: {
        id: number;
        workspace_id: number;
        name: string;
        color: string;
        position: number;
        capabilities: unknown;
        features: unknown;
        is_default: number;
        created: number;
    };
    workspace_secret_keys: {
        workspace_id: number;
        dek_wrapped: string;
        created: number;
        updated: number;
    };
    workspaces: {
        id: number;
        kind: 'personal' | 'shared';
        name: string;
        logo: string;
        owner_user_id: number;
        features: unknown;
        created: number;
        theme: string | null;
        home_layout: string | null;
    };
}

export type TableName = keyof Tables;
