#!/usr/bin/env bash
#
# Remove the agent's build artifacts: cargo's target/ and dist/ (the binaries
# from build-all.sh). Both are fully regenerated by a build.
#
set -euo pipefail
cd "$(dirname "$0")"

# Size about to be freed, for the summary (best-effort).
freed=$(du -shc target dist 2>/dev/null | tail -1 | awk '{print $1}')

# Prefer `cargo clean` (it owns the target/ layout); fall back to rm if cargo
# isn't on PATH (e.g. a rustup/Homebrew PATH mixup).
if command -v cargo >/dev/null 2>&1; then
    cargo clean
else
    rm -rf target
fi
rm -rf dist

echo "✓ Cleaned agent/target and agent/dist (freed ~${freed:-0})."
