/**
 * Domaines de messagerie jetable.
 *
 * Liste **embarquée** plutôt que téléchargée : elle bouge lentement, et la
 * dépendre d'un service tiers ferait dépendre une réponse locale et instantanée
 * de la disponibilité d'un dépôt GitHub. Volontairement courte et centrée sur
 * les fournisseurs réellement rencontrés — une liste de 100 000 entrées coûterait
 * de la mémoire pour un gain marginal, et le drapeau n'est de toute façon qu'un
 * signal parmi d'autres dans le score.
 */
export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
    '0-mail.com',
    '10minutemail.com',
    '10minutemail.net',
    '20minutemail.com',
    'anonbox.net',
    'armyspy.com',
    'burnermail.io',
    'cuvox.de',
    'dayrep.com',
    'discard.email',
    'dispostable.com',
    'einrot.com',
    'emailondeck.com',
    'fakeinbox.com',
    'fakemailgenerator.com',
    'gerinet.com',
    'getairmail.com',
    'getnada.com',
    'grr.la',
    'guerrillamail.biz',
    'guerrillamail.com',
    'guerrillamail.de',
    'guerrillamail.info',
    'guerrillamail.net',
    'guerrillamail.org',
    'guerrillamailblock.com',
    'harakirimail.com',
    'inboxbear.com',
    'incognitomail.com',
    'jetable.org',
    'mail-temporaire.fr',
    'mail7.io',
    'mailcatch.com',
    'maildrop.cc',
    'mailexpire.com',
    'mailinator.com',
    'mailnesia.com',
    'mailsac.com',
    'mailtemp.info',
    'mintemail.com',
    'moakt.com',
    'mohmal.com',
    'mytemp.email',
    'nowmymail.com',
    'sharklasers.com',
    'spam4.me',
    'spamgourmet.com',
    'temp-mail.io',
    'temp-mail.org',
    'tempail.com',
    'tempinbox.com',
    'tempmail.com',
    'tempmail.net',
    'tempmailaddress.com',
    'tempr.email',
    'throwawaymail.com',
    'tmail.ws',
    'trashmail.com',
    'trashmail.de',
    'trashmail.me',
    'trashmail.net',
    'tuta.io',
    'yopmail.com',
    'yopmail.fr',
    'yopmail.net'
]);
